### ISSUE TITLE
ImportError: No module named label_studio_ml.api

### ISSUE THREAD

**Issue by whisere** [heartexlabs/label-studio-ml-backend#10]
run cd label-studio-ml-backend
pip install -e .
cd label_studio_ml/examples
pip install -r requirements.txt
and label-studio-ml init my_ml_backend --script label_studio_ml/examples/simple_text_classifier.py
following the instructions but received:

label-studio-ml start my_ml_backend/
Traceback (most recent call last):
  File "./my_ml_backend/_wsgi.py", line 30, in <module>
    from label_studio_ml.api import init_app
ImportError: No module named label_studio_ml.api

**Comment by whisere** [comment]
This is due to default python need to link to python3 
ln -s -f /usr/local/bin/python3 /usr/bin/python

**Comment by gracelia** [comment]
> ln -s -f /usr/local/bin/python3 /usr/bin/python

My default python version is 3.8 at local, but still have this issue.

**Comment by gracelia** [comment]
After upgrade python to 3.8, go back to the first step, run 'pip install -r requirements.txt' again and everything performs perfectly.

**Comment by flavienbwk** [comment]
> This is due to default python need to link to python3
> ln -s -f /usr/local/bin/python3 /usr/bin/python

A more simpler way is to edit [server.py](https://github.com/heartexlabs/label-studio-ml-backend/blob/1bb4890cd688bdbf8a47afe4d41a8b6ff49feb05/label_studio_ml/server.py#L112), line 112 and change `python` to `python3` for example
