### ISSUE TITLE
`ValueError: empty vocabulary; perhaps the documents only contain stop words` on text classification tutorial

### ISSUE THREAD

**Issue by shpigunov** [heartexlabs/label-studio-ml-backend#105]
I am trying to go through this tutorial:
https://labelstud.io/tutorials/sklearn-text-classifier.html

I'm taking the model code practically verbatim, and am using a fairly straightforward interface:
```
<View>
  <Text name="text" value="$text"/>
  <View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;">
    <Header value="Choose text sentiment"/>
    <Choices name="sentiment" toName="text" choice="single" showInLine="true">
    <Choice value="no_pets"/><Choice value="pets"/></Choices>
  </View>
</View>
```

I've been able to launch and connect the backend in dev mode successfully, but upon each request it gives me an error as follows:

```
.../labelstudio/tfidf_backend/model3.py", line 148, in fit
    self.model.fit(input_texts, output_labels_idx)
...site-packages/sklearn/feature_extraction/text.py", line 1134, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

my `completions` in the fit function is apparently empty on every call, no matter what I do. This happens for both for "Train" via the interface, and for each annotation.

What am I dong wrong?

**Comment by makseq** [comment]
@shpigunov Sorry for such a long answer. Could you please update LS and ml backend to the latest versions and check it again? Looks like you used very outdated versions, `completions` field was deprecated 1.5 year ago.
