### ISSUE TITLE
404 error after label-studio-ml start my_ml_backend

### ISSUE THREAD

**Issue by whisere** [heartexlabs/label-studio-ml-backend#11]
run label-studio-ml start my_ml_backend successfully but reported 404 error:

 * Serving Flask app "label_studio_ml.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2021-04-06 12:16:04,800] [INFO] [werkzeug::_log::113]  * Running on http://0.0.0.0:9090/ (Press CTRL+C to quit)
[2021-04-06 12:16:11,130] [INFO] [werkzeug::_log::113] 127.0.0.1 - - [06/Apr/2021 12:16:11] "GET / HTTP/1.1" 404 -
[2021-04-06 12:16:12,330] [INFO] [werkzeug::_log::113] 127.0.0.1 - - [06/Apr/2021 12:16:12] "GET / HTTP/1.1" 404 -
[2021-04-06 12:16:43,845] [INFO] [werkzeug::_log::113] 127.0.0.1 - - [06/Apr/2021 12:16:43] "GET / HTTP/1.1" 404 -

**Comment by whisere** [comment]
And don't see this:
"Getting predictions
You should see model predictions in a labeling interface."

https://labelstud.io/tutorials/sklearn-text-classifier.html

**Comment by gracelia** [comment]
same situation again

**Comment by whisere** [comment]
Need to setup the right label setting with the correct py file, then it will need to enable under the model training menu item (under a different menu not the labeling interface above)

**Comment by hvassard** [comment]
I'm facing the same error 404 when trying to visit http://0.0.0.0:9090/ in the "Quickstart" guide (https://labelstud.io/guide/ml.html)
@whisere did you succeed to fix it ?
I also (not surprisingly) get an error when trying to use this link in the "Add a model" part in LabelStudio.

![image](https://user-images.githubusercontent.com/55416733/115038333-b9597a80-9ecf-11eb-84b9-9b367012d0c0.png)

**Comment by hvassard** [comment]
I just solved my problem realizing that my labeling configurations in LabelStudio settings + data i used were images whereas the ML backend I tried to connect was about processing text. Now it works :) I still have error 404 while visiting localhost:9090 but actually it doesn't mean it isn't working : try to visit http://0.0.0.0:9090/health and see if you have something (it should be the case).

**Comment by KonstantinKorotaev** [comment]
I have created a pull request with a small fix: 
https://github.com/heartexlabs/label-studio-ml-backend/pull/20

You won't have error 404 while visiting localhost:9090, it will show you health status of the ML backend
