### ISSUE TITLE
Bug / Potential error in the documentation - GET/POST /predict request

### ISSUE THREAD

**Issue by FelixJuch** [heartexlabs/label-studio-ml-backend#111]
In the docs:
https://labelstud.io/guide/ml.html#Get-predictions-from-a-model

There is the paragraph:

If you want to retrieve predictions manually for a list of tasks using only an ML backend, make a GET request to the /predict URL of your ML backend with a payload of the tasks that you want to see predictions for, formatted like the following example: [...]

With a GET request I get the following Error: 
requests.exceptions.HTTPError: 405 Client Error: METHOD NOT ALLOWED

But with a POST request it seams to work just fine.

**Comment by makseq** [comment]
@FelixJuch Thank you very much, it's a misspell. I will fix it asap.

**Comment by makseq** [comment]
Fixed: https://github.com/heartexlabs/label-studio/pull/2298/files
