### ISSUE TITLE
in my ml-backend , the model's function: fit()  gets the parameter "completions" is null

### ISSUE THREAD

**Issue by lglong123** [heartexlabs/label-studio-ml-backend#113]
def fit(self, completions, workdir=None,train_logs=None, **kwargs):
        print(completions)   # ()
        print(f"geted data size(item): {len(completions)}")   # geted data size(item): 0

**Comment by makseq** [comment]
We renamed `completions` ~1 year ago to `annotations`. Where did you get this code?

**Comment by lglong123** [comment]
it solved in this issuse: https://github.com/heartexlabs/label-studio-ml-backend/issues/99#issuecomment-1084823530

but , Task can only be obtained through task ID by this API : GET /api/tasks/{id}/

I want to train my backend model use all annotated tasks, so , How to use API to get all annotated tasks? 

Thanks for your answer.

**Comment by makseq** [comment]
You can try to call GET /api/tasks/?project=<id>.
