### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL '/data/upload/frame_0176.jpg': No schema supplied. Perhaps you meant http:///data/upload/frame_0176.jpg?

### ISSUE THREAD

**Issue by silverlining21** [heartexlabs/label-studio-ml-backend#12]
I am try out the mmdetection example, but failed to reproduce it. Here is the error from log `label-studio-ml` backends. follwing my steps:

- label-studio-ml init coco-detector --from /label-studio-ml-backend/label_studio_ml/examples/mmdetection/mmdetection.py

- nohup label-studio-ml start coco-detector --with config_file=/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoint_file=/installer/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth score_threshold=0.5 device=cuda:0 > ml.log &

- nohup  label-studio start my_project --username test@localhost --password test --init --ml-backends http://localhost:9090 > fornt.log &

To be added, my data imported through the web, the detail web screenshot located here [https://github.com/heartexlabs/label-studio-ml-backend/issues/8#issuecomment-818542737](url)
 
env:
``` 
=> Database and media directory: /root/.local/share/label-studio
=> Static URL is set to: /static/


Label Studio version: 1.0.1

{
    "package": {
        "version": "1.0.1",
        "short_version": "1.0",
        "latest_version_from_pypi": "1.0.1",
        "latest_version_upload_time": "2021-04-05T19:13:41",
        "current_version_is_outdated": false
    },
    "backend": {
        "message": "Updates for relative URLs (#752)",
        "commit": "71278b0b727bc103f408fe3c279c5487f44fee56",
        "date": "2021-04-05 11:30:54 -0700",
        "branch": "master",
        "version": "1.0.0+87.g71278b0b"
    },
    "label-studio-frontend": {
        "message": "Fix Text spans if label's missing for any reason",
        "commit": "5164462ced2fe8a0bbdd7cd9c4a5bec3772577ab",
        "branch": "master",
        "date": "2021-03-31T10:57:00Z"
    },
    "dm2": {
        "message": "Annotation generation logic fix",
        "commit": "7751a996682f145d651123af27286f4f392c293c",
        "branch": "master",
        "date": "2021-04-02T13:15:22Z"
    }
}

```

Any suggesion would be appericiated!

**Comment by makseq** [comment]
@silverlining21 Hope this issue is fixed now.
