### ISSUE TITLE
Cannot set model_version

### ISSUE THREAD

**Issue by GaaH** [heartexlabs/label-studio-ml-backend#121]
Is there a way to specify the `model_version` field?
I cannot find how to setup this field at the model level. It seems that it can be set on the prediction level by specifying `model_version` next to to `result` fied in the JSON output of the model, but it is ignored by Label-Studio in favour of the randomly generated version number.

**Comment by KonstantinKorotaev** [comment]
Hi @GaaH 
You can modify it through import\export:
1. Export your tasks
2. Modify model_version in json file 
3. Import your tasks into Label Studio

**Comment by Goschjann** [comment]
running into the same problem as well - is there any other way then the heuristic described by @KonstantinKorotaev (thanks)?

**Comment by makseq** [comment]
@Goschjann do you use ML Backend and it generates predictions? As I remember you have to specify model_version in the dict that will be returned after model training in `fit()`.
