### ISSUE TITLE
This repo is too complex

### ISSUE THREAD

**Issue by flavienbwk** [heartexlabs/label-studio-ml-backend#13]
Hi,

I try to get started with ML Backend in Label Studio.
My personal appreciation is that the example provided by this repo is too complex :

- The docker and docker-compose configurations should be at the root of the repo (Docker is a standard and should probably be the one for LabelStudio)
- The repo should provide 1 or 2 simple examples (text and image classification for example)
- There are several requirements.txt, there should be only one (you could add comments in the `requirements.txt` for each example's dependencies)

Currently it's very time consuming to get into ML Backend even if it's a critical feature for labelers.

I hope Heartex can make it more simple in the future (I guess you are very busy).

Thanks,
_A really-liking-label-studio user_

**Comment by davodogster** [comment]
I'm also interested in instance segmentation and semantic segmentation examples. The current MMdetection example only mentions Bounding box.

**Comment by niklub** [comment]
Hey, guys, do think it would be easier if we put every model example in a separate repo? With clear commands how to setup its own environment.  Like [this one](https://github.com/heartexlabs/label-studio-transformers)

**Comment by makseq** [comment]
Closed as outdated and probably solved.
