### ISSUE TITLE
Missing JSON imports; bad test; BERT `reset_model` is no-op; Electra global misused

### ISSUE THREAD

**Issue by lmmx** [heartexlabs/label-studio-ml-backend#137]
I read through these examples and really appreciate the material :clap: 

After studying it a bit 'by eye' I cloned the repo and ran some linting on it, which allowed me to use `flake8` to check code quality (without a bunch of stylistic warnings), and it did flag up a basic undefined name bug in the following modules

```
./examples/flair/_wsgi.py:38:18: F821 undefined name 'json'
./examples/huggingface/_wsgi.py:38:18: F821 undefined name 'json'
./examples/mmdetection/_wsgi.py:38:18: F821 undefined name 'json'
./examples/the_simplest_backend/_wsgi.py:37:18: F821 undefined name 'json'
./examples/dummy_model/_wsgi.py:38:18: F821 undefined name 'json'
./examples/bert/_wsgi.py:38:18: F821 undefined name 'json'
./examples/nemo/_wsgi.py:38:18: F821 undefined name 'json'
./examples/substring_matching/_wsgi.py:38:18: F821 undefined name 'json'
./examples/tensorflow/_wsgi.py:38:18: F821 undefined name 'json'
./examples/simple_text_classifier/_wsgi.py:38:18: F821 undefined name 'json'
./examples/pytorch_transfer_learning/_wsgi.py:38:18: F821 undefined name 'json'
./examples/ner/_wsgi.py:38:18: F821 undefined name 'json'
./examples/electra/_wsgi.py:38:18: F821 undefined name 'json'
./examples/tesseract/_wsgi.py:38:18: F821 undefined name 'json'
```

This can be fixed on Linux by running:

```sh
find . -name "_wsgi.py" -exec sed -i '1i import json' {} +
```

or on Mac by running:

```sh
find . -name "_wsgi.py" -execf sed -i '1i import json' {} +
```

---

Additionally the `flake8` linter picked up a reassigned name in `label_studio_ml/tests/test_basic.py` at line 75, which appears to be a mistakenly pasted test (there are already setup tests for both `the_simplest_backend` and `simple_text_classifier`). The fix for this is to delete these lines (note also the mismatch in `ML_BACKEND` and `reason` in the pytest `skipif` decorator).

```py
@pytest.mark.second
@pytest.mark.skipif(
    ML_BACKEND != "the_simplest_backend", reason="Test for simple_text_classifier"
)
def test_setup_the_simplest_backend():
    data = {
        "project": "1.1654592272",
        "schema": '<View><Text name="text" value="$transcript"/><View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;"><Header value="Choose text sentiment"/><Choices name="sentiment" toName="text" choice="single" showInLine="true"><Choice value="Positive"/><Choice value="Negative"/><Choice value="Neutral"/></Choices></View></View>',
        "hostname": "http://localhost:8080",
        "access_token": "1234567890123456789012345678901234567890",
    }
    response = requests.post("http://127.0.0.1:9090/setup", json=data)
    assert response.status_code == 200
```

---

Another thing I'm pretty sure must be a bug is that the `reset_model` method of the `bert` example backend does not reassign `self.model`, it returns the model, but when it is called nothing is done with the return value.

https://github.com/heartexlabs/label-studio-ml-backend/blob/da749151ca59b2d60b23cf3b60864592d7df50d7/label_studio_ml/examples/bert/bert_classifier.py#L54-L56

I'm still in the midst of figuring out how this should work as a cohesive application but this is surely a futile computation, which may mean it's not a good example to use as a template.

---

Additionally (again minor nit) noticed the Electra model does not use the hardcoded `MODEL_FILE` to load from after checking if the path exists.

https://github.com/heartexlabs/label-studio-ml-backend/blob/da749151ca59b2d60b23cf3b60864592d7df50d7/label_studio_ml/examples/electra/electra.py#L31-L32

Should be

```py
        if os.path.exists(MODEL_FILE):
            self.model = ElectraForSequenceClassification.from_pretrained(MODEL_FILE)
```

**Comment by makseq** [comment]
@lmmx thanks for your report! Could you please create a PR?

**Comment by lmmx** [comment]
Sure can!

**Comment by lmmx** [comment]
PR in at #139 :wrench:
