### ISSUE TITLE
Increase the timeout in HTTPConnectionPool()

### ISSUE THREAD

**Issue by pinecho** [heartexlabs/label-studio-ml-backend#140]
Hello,
I am wondering where can I set the **timeout parameter** for the HTTPConnectionPool().
It occurred a ValidationError when I tried to add a model:
![image](https://user-images.githubusercontent.com/37013626/179371230-9cd74a72-0807-4397-8b27-645d2c873051.png)

Here is the log of the backend:
```
[2022-07-16 21:36:15,918] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [16/Jul/2022 21:36:15] "GET /health HTTP/1.1" 200 -
###【Loading model...】
###【Finish Loading model from label_studio_ml/examples/my_segment/mask_rcnn_R_50_FPN_1x.yaml label_studio_ml/examples/my_segment/mask_rcnn_R_50_FPN_1x.yaml on cpu 】
[2022-07-16 21:36:24,047] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [16/Jul/2022 21:36:24] "POST /setup HTTP/1.1" 200 -
```

**The model can be successfully loaded, but it takes a little longer time(about 7 seconds) because it is on cpu.**
`read timeout=3.0` is too short for loading, where can I change this parameter?

Thank you.

**Comment by pinecho** [comment]
@makseq @KonstantinKorotaev
Could you please check the problem? Thank you.

**Comment by KonstantinKorotaev** [comment]
Hi @pinecho 
Add this environment variable ML_TIMEOUT_SETUP in seconds and restart Label Studio.

**Comment by pinecho** [comment]
It works, thanks so much!
