### ISSUE TITLE
Tesseract - empty context - unable to predict

### ISSUE THREAD

**Issue by sriharshamanne** [heartexlabs/label-studio-ml-backend#142]
Hi,
I am trying to setup label studio with tesseract.
When interface is setup/trying to predict, i am getting below error - context is None - unable to predict .

"ml.models::predict_tasks::179] [WARNING] ML backend returned empty prediction for project  (id=5, url=http://localhost:9090/)"

" (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at xx
Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')'"

When i print in tesseract.py - predict method -
"task {'id': 1, 'data': {'ocr': '/data/upload/1/340ce33a-download.png'}, 'meta': {}, 'created_at': '2022-07-xxx', 'updated_at': '2022-07-xxx', 'is_labeled': False, 'overlap': 1, 'project': 1, 'file_upload': 1, 'annotations': [], 'predictions': []}
img_path_url /data/upload/1/340ce33a-download.png
context None"

Please help on how to solve this.

Note - http://localhost:9090/health is up and fine.
When tried directly from python using command, tesseract is able to predict.

**Comment by KonstantinKorotaev** [comment]
Hi @sriharshamanne 
Do you use interactive annotations?

**Comment by sriharshamanne** [comment]
@KonstantinKorotaev No. Trying to annotate simple static image

**Comment by KonstantinKorotaev** [comment]
@sriharshamanne tesseract example is used in interactive annotating scenario and expects context in input data.
You can modify it extracting data from annotations. Check [this example](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/simple_text_classifier/simple_text_classifier.py#L70).

**Comment by wujushan** [comment]
@sriharshamanne I am facing the same issue. Did you solve it?

**Comment by sriharshamanne** [comment]
@wujushan No. I tried in interactive scenario. Could not solve it.

**Comment by KonstantinKorotaev** [comment]
@wujushan @sriharshamanne 
What LS version do you use?
There was a bug when FE side made 2 requests to ML backend and second request was with empty context.

**Comment by sriharshamanne** [comment]
Using LS 1.4

**Comment by KonstantinKorotaev** [comment]
Could you please upgrade to the latest LS and check?

**Comment by dimonixx** [comment]
I'm trying to make it work with 1.7.2, the context is always empty.
