### ISSUE TITLE
Dependency conflict installing label-studio-ml-backend in Conda environment

### ISSUE THREAD

**Issue by Bramklaassen** [heartexlabs/label-studio-ml-backend#144]
Hi, I am trying to install label-studio-ml-backend into my Conda environment where I also installed label-studio, but I am getting a dependency conflict:

`label-studio-ml 1.0.8 requires label-studio-tools==0.0.0.dev11, but you have label-studio-tools 0.0.0.dev14 which is incompatible.`

I tried fixing it by downgrading to 0.0.0.dev11 (`pip install -I label-studio-tools==0.0.0.dev11`), but then I get the following error:

`label-studio 1.5.0.post0 requires label-studio-tools==0.0.0.dev14, but you have label-studio-tools 0.0.0.dev11 which is incompatible.`

I tried this in Conda environments with Python version 3.7, 3.8, 3.9 and 3.10, but without succes (pip version 22.1.2)...

Any idea how I can fix this dependency conflict?

**Comment by makseq** [comment]
It's recommended to use separate environments for LS and LS ML backend. Or even better to use docker-compose for ML backends.

**Comment by Bramklaassen** [comment]
Thanks, using separate environments works!
