### ISSUE TITLE
The provided simple text classifier example didn't work

### ISSUE THREAD

**Issue by jingsongs** [heartexlabs/label-studio-ml-backend#145]
I am using the provided example of simple text classifier.I met an error:

[2022-08-08 15:04:14,037] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/ocr/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/ocr/label-studio-ml-backend/label_studio_ml/api.py", line 70, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/home/ocr/label-studio-ml-backend/label_studio_ml/model.py", line 689, in train
    cls.get_or_create(project, label_config, force_reload=True, train_output=train_output)
  File "/home/ocr/label-studio-ml-backend/label_studio_ml/model.py", line 491, in get_or_create
    if not cls.has_active_model(project) or force_reload or (cls.get(project).model_version != version and version is not None):  # noqa
  File "/home/ocr/label-studio-ml-backend/label_studio_ml/model.py", line 453, in has_active_model
    return cls._key(project) in cls._current_model
TypeError: argument of type 'ModelWrapper' is not iterable

**Comment by pabvald** [comment]
I get the same error

**Comment by KonstantinKorotaev** [comment]
What version of ML backend do you use?

**Comment by jingsongs** [comment]
I just followed the steps written in the readme.md. It may be the latest verison in github.
![image](https://user-images.githubusercontent.com/25786748/183544817-78b20f96-9f5d-48b2-aca5-9ce10b0a3a6d.png)
                           Thank you very much.

**Comment by jingsongs** [comment]
> What version of ML backend do you use?

I just followed the steps written in the readme.md. It may be the latest verison in github.
![image](https://user-images.githubusercontent.com/25786748/183545967-811fde1c-14ad-44d8-b703-2032bc54aaa0.png)
Thank you very much.

**Comment by KonstantinKorotaev** [comment]
Could you please raise ML backend verion to 1.0.8 in requirements file?

**Comment by Bramklaassen** [comment]
Got the same issue; the problem lies in `model.py`. The `cls._current_model` is treated as a dict throughout the code except for the `fetch` and `predict` methods. In `fetch` the `cls._current_model` is set directly to a `ModelWrapper` intance, where it should have been added to the dict instead. The `predict` method also accesses `cls._current_model` directly as a `ModelWrapper`.

This applies to version 1.0.8 by the way.

**Comment by pabvald** [comment]
Maybe the error lays on the model not being run with `LABEL_STUDIO_ML_BACKEND_V2=True`. In theory it is to `True` by default, but when the reality is that the model is running like this: 
```json
{"model_dir":"C:\\Users\\pablo\\DFKI\\annotation-pipeline\\ml_backend","status":"UP","v2":false}
```

**Comment by jingsongs** [comment]
> requirements file?

**Comment by jingsongs** [comment]
> Could you please raise ML backend verion to 1.0.8 in requirements file?
The label-studio-ml library version is 1.0.8 in my machine, like this:
      label-studio-ml          1.0.8               /home/ocr/label-studio-ml-backend
      label-studio-tools       0.0.0.dev11

**Comment by jingsongs** [comment]
> Maybe the error lays on the model not being run with `LABEL_STUDIO_ML_BACKEND_V2=True`. In theory it is to `True` by default, but the reality is that the model is running like this:
> 
> ```json
> {"model_dir":"C:\\Users\\path\\ml_backend","status":"UP","v2":false}
> ```

I change the option from False to True in model.py. But the logs told me that may be the trained model isn't loaded correctly.
logs:
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           12     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.29584D+00    |proj g|=  6.66667D-01

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   12      5      6      1     0     0   4.905D-06   1.076D+00
  F =   1.0758781351996998     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
Initialized with from_name=sentiment, to_name=text, labels=['Positive', 'Negative', 'Neutral']
Label set has been changed:['Negative', 'Positive']
Start training on 4 samples
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           28     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.77259D+00    |proj g|=  2.15018D-01

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   28      8     10      1     0     0   2.020D-05   1.380D+00
  F =   1.3795684598303819     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
Save model to ./my_ml_backend/3.1659670579/1660097310/b49929f7.pkl
Loaded from train output with from_name=sentiment, to_name=text, labels=['Negative', 'Positive']
[2022-08-10 10:08:30,088] [INFO] [werkzeug::_log::225] 172.17.0.2 - - [10/Aug/2022 10:08:30] "POST /train HTTP/1.1" 201 -
[2022-08-10 10:08:30,204] [INFO] [werkzeug::_log::225] 172.17.0.2 - - [10/Aug/2022 10:08:30] "GET /health HTTP/1.1" 200 -
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           12     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.29584D+00    |proj g|=  6.66667D-01

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   12      5      6      1     0     0   4.905D-06   1.076D+00
  F =   1.0758781351996998     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
Initialized with from_name=sentiment, to_name=text, labels=['Positive', 'Negative', 'Neutral']
[2022-08-10 10:08:30,233] [INFO] [werkzeug::_log::225] 172.17.0.2 - - [10/Aug/2022 10:08:30] "POST /setup HTTP/1.1" 200 -

**Comment by jingsongs** [comment]
> Could you please raise ML backend verion to 1.0.8 in requirements file?
I got your mean!!!  The error disappears with  the code of 1.0.8 version.
![image](https://user-images.githubusercontent.com/25786748/183877186-77fefbf8-7558-4742-bd94-36c5c84496a2.png)
