### ISSUE TITLE
How to resolve validation error on label studio UI

### ISSUE THREAD

**Issue by driggeraaliya94** [heartexlabs/label-studio-ml-backend#147]
Hi,
I am facing this issue when I try to connect my ml-backend-model with the label-studio.
Validation error

    Successfully connected to http://localhost:8080 but it doesn't look like a valid ML backend. Reason: 404 Client Error: Not Found for url: http://localhost:8080/setup.
    Check the ML backend server console logs to check the status. There might be
    something wrong with your model or it might be incompatible with the current labeling configuration.
    
![Screenshot from 2022-08-10 11-28-44](https://user-images.githubusercontent.com/109962218/183826439-a5397d78-46b0-49fc-8bfc-70fdbb7365af.png)

    I have also checked the logs and got these errors in the logs. Can anyone please help with this?

**Comment by KonstantinKorotaev** [comment]
Hi @driggeraaliya94 
What label config do use for your project?

**Comment by driggeraaliya94** [comment]
model.py:



class SimpleTextClassifier(LabelStudioMLBase):

    def __init__(self, **kwargs):
        # don't forget to initialize base class...
        super(SimpleTextClassifier, self).__init__(**kwargs)

        # then collect all keys from config which will be used to extract data from task and to form prediction
        # Parsed label config contains only one output of <Choices> type
        assert len(self.parsed_label_config) == 1
        self.from_name, self.info = list(self.parsed_label_config.items())[0]
        assert self.info['type'] == 'Choices'

        # the model has only one textual input
        assert len(self.info['to_name']) == 1
        assert len(self.info['inputs']) == 1
        assert self.info['inputs'][0]['type'] == 'Text'
        self.to_name = self.info['to_name'][0]
        self.value = self.info['inputs'][0]['value']

        if not self.train_output:
            # If there is no trainings, define cold-started the simple TF-IDF text classifier
            self.reset_model()
            # This is an array of <Choice> labels
            self.labels = self.info['labels']
            # make some dummy initialization
            self.model.fit(X=self.labels, y=list(range(len(self.labels))))
            print('Initialized with from_name={from_name}, to_name={to_name}, labels={labels}'.format(
                from_name=self.from_name, to_name=self.to_name, labels=str(self.labels)
            ))
        else:
            # otherwise load the model from the latest training results
            self.model_file = self.train_output['model_file']
            with open(self.model_file, mode='rb') as f:
                self.model = pickle.load(f)
            # and use the labels from training outputs
            self.labels = self.train_output['labels']
            print('Loaded from train output with from_name={from_name}, to_name={to_name}, labels={labels}'.format(
                from_name=self.from_name, to_name=self.to_name, labels=str(self.labels)
            ))

    def reset_model(self):
        self.model = make_pipeline(TfidfVectorizer(ngram_range=(1, 3), token_pattern=r"(?u)\b\w\w+\b|\w"), LogisticRegression(C=10, verbose=True))

    def predict(self, tasks, **kwargs):
        # collect input texts
        input_texts = []
        for task in tasks:
            input_text = task['data'].get(self.value) or task['data'].get(DATA_UNDEFINED_NAME)
            input_texts.append(input_text)

        # get model predictions
        probabilities = self.model.predict_proba(input_texts)
        print('=== probabilities >', probabilities)
        predicted_label_indices = np.argmax(probabilities, axis=1)
        predicted_scores = probabilities[np.arange(len(predicted_label_indices)), predicted_label_indices]
        predictions = []
        for idx, score in zip(predicted_label_indices, predicted_scores):
            predicted_label = self.labels[idx]
            # prediction result for the single task
            result = [{
                'from_name': self.from_name,
                'to_name': self.to_name,
                'type': 'choices',
                'value': {'choices': [predicted_label]}
            }]

            # expand predictions with their scores for all tasks
            predictions.append({'result': result, 'score': score})

        return predictions

    def _get_annotated_dataset(self, project_id):
        """Just for demo purposes: retrieve annotated data from Label Studio API"""
        download_url = f'{HOSTNAME.rstrip("/")}/api/projects/{project_id}/export'
        response = requests.get(download_url, headers={'Authorization': f'Token {API_KEY}'})
        if response.status_code != 200:
            raise Exception(f"Can't load task data using {download_url}, "
                            f"response status_code = {response.status_code}")
        return json.loads(response.content)

    def fit(self, annotations, workdir=None, **kwargs):
        # check if training is from web hook
        if kwargs.get('data'):
            project_id = kwargs['data']['project']['id']
            tasks = self._get_annotated_dataset(project_id)
        # ML training without web hook
        else:
            tasks = annotations

        input_texts = []
        output_labels, output_labels_idx = [], []
        label2idx = {l: i for i, l in enumerate(self.labels)}

        for task in tasks:
            if not task.get('annotations'):
                continue
            annotation = task['annotations'][0]
            # get input text from task data
            if annotation.get('skipped') or annotation.get('was_cancelled'):
                continue

            input_text = task['data'].get(self.value) or task['data'].get(DATA_UNDEFINED_NAME)
            input_texts.append(input_text)

            # get an annotation
            output_label = annotation['result'][0]['value']['choices'][0]
            output_labels.append(output_label)
            output_label_idx = label2idx[output_label]
            output_labels_idx.append(output_label_idx)

        new_labels = set(output_labels)
        if len(new_labels) != len(self.labels):
            self.labels = list(sorted(new_labels))
            print('Label set has been changed:' + str(self.labels))
            label2idx = {l: i for i, l in enumerate(self.labels)}
            output_labels_idx = [label2idx[label] for label in output_labels]

        # train the model
        print(f'Start training on {len(input_texts)} samples')
        self.reset_model()
        self.model.fit(input_texts, output_labels_idx)

        # save output resources
        workdir = workdir or os.getenv('MODEL_DIR')
        model_name = str(uuid4())[:8]
        if workdir:
            model_file = os.path.join(workdir, f'{model_name}.pkl')
        else:
            model_file = f'{model_name}.pkl'
        print(f'Save model to {model_file}')
        with open(model_file, mode='wb') as fout:
            pickle.dump(self.model, fout)

        train_output = {
            'labels': self.labels,
            'model_file': model_file
        }
        return train_output


label config:

<View>
  <Text name="news" value="$text"/>
  <Choices name="topic" toName="news">
    <Choice value="Politics"/>
    <Choice value="Technology"/>
    <Choice value="Sport"/>
    <Choice value="Weather"/>
  </Choices>
</View>




These are my model.py file and label config, I am able to connect my ml-backend with label-studio and pre-annotate the data. I am still getting TypeError and keyError even when the process is working fine. Is it required to solve this error because I am able to annotate data automatically and backend is connected successfully?


attaching below the screenshot of the terminal.

errors:

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
Save model to /home/ubuntu/Pictures/Screenshots/ml_backend_10aug/label-studio-ml-backend/./backend_3/1660197151/e4bcfa63.pkl
[2022-08-11 11:22:38,670] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "GET /health HTTP/1.1" 200 -
[2022-08-11 11:22:38,694] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "GET /health HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:38,715] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "POST /setup HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:38,741] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "POST /setup HTTP/1.1" 200 -
[2022-08-11 11:22:38,820] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "GET /health HTTP/1.1" 200 -
[2022-08-11 11:22:38,854] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "GET /health HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:38,890] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "POST /setup HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:38,922] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "POST /setup HTTP/1.1" 200 -
[2022-08-11 11:22:38,964] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "GET /health HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:38,983] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:38] "POST /setup HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
Start training on 5 samples
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =          411     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  5.49306D+00    |proj g|=  1.33333D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  411     11     12      1     0     0   2.830D-05   1.693D+00
  F =   1.6927267892543973     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
Save model to /home/ubuntu/Pictures/Screenshots/ml_backend_10aug/label-studio-ml-backend/./backend_3/9.1660137216/1660197160/bdaf0087.pkl
[2022-08-11 11:22:40,813] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/api.py", line 70, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 667, in train
    cls.get_or_create(project, label_config, force_reload=True, train_output=train_output)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 471, in get_or_create
    if not cls.has_active_model(project) or force_reload or (cls.get(project).model_version != version and version is not None):  # noqa
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 447, in has_active_model
    return cls._key(project) in cls._current_model
TypeError: argument of type 'ModelWrapper' is not iterable

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/api.py", line 70, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 667, in train
    cls.get_or_create(project, label_config, force_reload=True, train_output=train_output)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 471, in get_or_create
    if not cls.has_active_model(project) or force_reload or (cls.get(project).model_version != version and version is not None):  # noqa
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 447, in has_active_model
    return cls._key(project) in cls._current_model
TypeError: argument of type 'ModelWrapper' is not iterable

[2022-08-11 11:22:40,814] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:40] "POST /train HTTP/1.1" 500 -
[2022-08-11 11:22:40,843] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:40] "GET /health HTTP/1.1" 200 -
Loaded from train output with from_name=topic, to_name=news, labels=['Politics', 'Sport', 'Weather']
[2022-08-11 11:22:40,847] [INFO] [werkzeug::_log::225] 127.0.0.1 - - [11/Aug/2022 11:22:40] "POST /setup HTTP/1.1" 200 -

**Comment by KonstantinKorotaev** [comment]
`TypeError: argument of type 'ModelWrapper' is not iterable`

Please update ML backend to 1.0.8

**Comment by driggeraaliya94** [comment]
> `TypeError: argument of type 'ModelWrapper' is not iterable`
> 
> Please update ML backend to 1.0.8

Thank you @KonstantinKorotaev

**Comment by hemangjoshi37a** [comment]
You need to compare that the two are equal, not that one is in the other.

in this file : ` /home/<YOUR_USER_NAME>/anaconda3/lib/python3.8/site-packages/label_studio_ml/model.py`

replace this line : `return cls._key(project) in cls._current_model`
to this line : 
```
are_they_equal = cls._key(project) == cls._current_model
return are_they_equal
```
https://hjlabs.in

**Comment by swatijibhkatesj** [comment]
how to update ml backend

**Comment by makseq** [comment]
```
pip install -U label-studio-ml
```
or 
https://github.com/heartexlabs/label-studio-ml-backend#quickstart

**Comment by swatijibhkatesj** [comment]
how can we work with enterprise version of label studio to leverage label studio's active learning feature?
when i connect ml-backend (from localhost) raised error "can't connect to localhost", is thare any solution?

**Comment by KonstantinKorotaev** [comment]
@swatijibhkatesj 
You need to publish your service somewhere and add it in LSE.

**Comment by swatijibhkatesj** [comment]
> @swatijibhkatesj You need to publish your service somewhere and add it in LSE.

you mean need to publish on cloud or something. Please suggest me some correct way.

**Comment by KonstantinKorotaev** [comment]
> you mean need to publish on cloud or something.

Yes, publish on cloud is the correct way

**Comment by qry0120** [comment]
> Hi, I am facing this issue when I try to connect my ml-backend-model with the label-studio. Validation error
> 
> ```
> Successfully connected to http://localhost:8080 but it doesn't look like a valid ML backend. Reason: 404 Client Error: Not Found for url: http://localhost:8080/setup.
> Check the ML backend server console logs to check the status. There might be
> something wrong with your model or it might be incompatible with the current labeling configuration.
> ```
> 
> ![Screenshot from 2022-08-10 11-28-44](https://user-images.githubusercontent.com/109962218/183826439-a5397d78-46b0-49fc-8bfc-70fdbb7365af.png)
> 
> ```
> I have also checked the logs and got these errors in the logs. Can anyone please help with this?
> ```

**Comment by KonstantinKorotaev** [comment]
Your simple text classifier is made for Choices.
If you have changed it - remove assertion in init method.
