### ISSUE TITLE
get_image_size bug

### ISSUE THREAD

**Issue by ChenPengf** [heartexlabs/label-studio-ml-backend#156]
When the picture has an EXIF information, the Image size may get the opposite value of the width and height, and Bboxes will generate an error coordinate. In order to solve this problem, I temporarily modified part of the code:
```python
def get_image_size(filepath):
    # return Image.open(filepath).size
    img = Image.open(filepath)
    img = ImageOps.exif_transpose(img)
    return img.size
```
Then, the returned results can be displayed normally in label-studio.

**Comment by makseq** [comment]
Could you please create a PR ?

**Comment by ChenPengf** [comment]
Hi, I have created a PR to fix this bug（https://github.com/heartexlabs/label-studio-ml-backend/pull/158）.

**Comment by makseq** [comment]
@ChenPengf https://github.com/heartexlabs/label-studio-ml-backend/pull/158#pullrequestreview-1090303202 please check this comment

**Comment by KonstantinKorotaev** [comment]
Merged into master
