### ISSUE TITLE
Change default work_dir for model annotation results

### ISSUE THREAD

**Issue by laxmimerit** [heartexlabs/label-studio-ml-backend#162]
Hi,
How can I change default location of annotations result which is being stored in the form of `.json`.
I want to change location of following directories which are being created in `cwd`.
![image](https://user-images.githubusercontent.com/16714612/190962031-d3a6137f-3d53-4a82-be3f-3bd2e952d669.png)

**Comment by KonstantinKorotaev** [comment]
In your init_app add param **model_dir** with the folder of your choice.
Check this [example](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/the_simplest_backend/_wsgi.py#L121).

**Comment by laxmimerit** [comment]
Thanks
