### ISSUE TITLE
Cannot find the file "label_studio_ml/examples/tesseract/ner_ml_backend.py"

### ISSUE THREAD

**Issue by wujushan** [heartexlabs/label-studio-ml-backend#163]
Do I need to write my own ner_ml_backend.py ?

**Comment by wujushan** [comment]
> Do I need to write my own ner_ml_backend.py ?

The ner_ml_backend.py is now the tesseract.py file.

**Comment by abhinavkulkarni** [comment]
Hi @wujushan,

The documentation (README.md) needs to be updated to reflect this.

**Comment by makseq** [comment]
@abhinavkulkarni thanks for pointing us again :) Done.
