### ISSUE TITLE
PolygonLabel not appearing on frontend

### ISSUE THREAD

**Issue by mcondor10** [heartexlabs/label-studio-ml-backend#166]
Hi! I am working on an integration of Detectron2 with Label Studio ML for instance segmentation. As label configuration I am using PolygonLabels. Right now the model is able to make predictions and send them to the frontend; sadly, while the predictions are listed on the right, they are not being drawn on the image. The only polygon that is being drawn is the last one, which I created manually. 

![image](https://user-images.githubusercontent.com/98813800/193826571-b89f8e1e-fe7c-4d6c-b865-4e009569339c.png)

This is the code for labeling interface that I am using:

```
<View>

  <Header value="Select label and click the image to start"/>
  <Image name="image" value="$image" zoom="true"/>

  <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
    <Label value="cell" background="blue"/>
  </PolygonLabels>

</View>
```

And this is the label format in the ML backend:

```
results.append({
      'from_name': self.from_name,
      'to_name': self.to_name,
      'original_width': img_width,
      'original_height': img_height,
      'type': 'polygonlabels',
      'value': {
          'points': polygon.tolist(),  # Format: [ [x, y], [x, y] ]
          'polygonlabels': ['cell']
      },
      'score': score
  })
```
Am I missing something? Any help would be appreciated.

**Comment by makseq** [comment]
@mcondor10 please show the final JSON for annotation, most likely you didn't convert coordinates to percents from 0 to 100. 
https://labelstud.io/guide/predictions.html#Units-of-image-annotations

**Comment by mcondor10** [comment]
> @mcondor10 please show the final JSON for annotation, most likely you didn't convert coordinates to percents from 0 to 100. https://labelstud.io/guide/predictions.html#Units-of-image-annotations

Hi! Sorry, I realized the percentage proportions were wrong, and that fixed it. Thanks!
