### ISSUE TITLE
Redis requirements

### ISSUE THREAD

**Issue by Davidnet** [heartexlabs/label-studio-ml-backend#175]
Hi!

Small question, it does seems that even to run example you need to have `redis`, I do not find it neither in the `requirements.txt` or the `setup.py` how that dependency (and all of redis-py packages) is specified?

Thanks for having this public

**Comment by KonstantinKorotaev** [comment]
Hi @Davidnet 

Which example are you referring to?

If you need redis in your setup - use docker-compose file in example folder
