### ISSUE TITLE
Using MMDetection as ML backend, but it can't deal with Semantic Segmentation

### ISSUE THREAD

**Issue by 870794501** [heartexlabs/label-studio-ml-backend#178]
Hi, I refer to https://labelstud.io/tutorials/object-detector.html
Firstly, I use Faster-RCNN, and the program works perfectly.
Then I want to doing some Semantic Segmentation, so I change the Faster-RCNN to Mask-RCNN. In Labeling Interface, choosing "Object Detection with Bounding Boxes" is OK. However,  I can't chose "Semantic Segmentation with Polygons" and "Semantic Segmentation with Masks", it shows:

_Created annotations are incompatible with provided labeling schema, we found:
4 with from_name=label, to_name=image, type=rectanglelabels_

Is there a way to use MMDetection deal with semantic segmentation？
Thanks a lot.

**Comment by VasilevGrigoriy** [comment]
@870794501 Did you find solution for that problem? I implement custom get_results in SAM model, but it does not show polygons in UI (in export there are all polygons)
