### ISSUE TITLE
should ml-backend be ran in the docker container?

### ISSUE THREAD

**Issue by mhyeonsoo** [heartexlabs/label-studio-ml-backend#180]
Hi,

Thanks for the great resources.
I am currently trying to deploy ml-backend running with label-studio.

So far, I have three questions about the overall process.

1. should ml-backend such as mmdetection, custom model backend be ran in the docker?
    If so, should it be the same docker container as label-studio?
    The reason why I am asking this is that I met the error like the below which is saying path mismatch (probably)
    
```
label-studio-ml-backend/.venv/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py", line 64, in get_local_path
    raise FileNotFoundError(filepath)
FileNotFoundError /my_images/image_2_1.jpg
```

2. What is the difference between **docker-compose** command and **label-studio-ml start** command
    I am wondering if this process is correct or not.
    - run docker-compose to generate docker container.
    - in the docker container, run label-studio init and start command to initiate custom ml-backend piepline.

3. When I tried to run ml-backend not using docker, but just connecting file path same as local and docker,
    I met the error message saying
    ```
    TypeError: n.filter is not a function
    ```
    When I click the image
    
    Attaching screenshot
    
![image](https://user-images.githubusercontent.com/32179857/204471059-40c889b3-7305-449b-bedb-d119104c5c8c.png)

Can you please take a look at the issues above and give me any suggestions?
Thanks again,

**Comment by makseq** [comment]
Hi, originally we were using `label-studio-ml start` directly in user's current environment. 
Then we decided to use docker-compose as official way to run ML backends, because there should be redis, some advanced builds of libs, etc. It's better to use docker here.
