### ISSUE TITLE
sh: python: command not found when following along with ml backend tutorial

### ISSUE THREAD

**Issue by kodecreer** [heartexlabs/label-studio-ml-backend#184]
I am following the label studio ml backend tutorial and when I try to start the ml backend it pulls up this error
`sh: python: command not found`

I have python3 installed and it's aliased as python. Which is confusing me a little bit.

**Comment by makseq** [comment]
Sorry, it's very unclear what command exactly and where you try to run commands..

**Comment by ZhangYuef** [comment]
> I am following the label studio ml backend tutorial and when I try to start the ml backend it pulls up this error `sh: python: command not found`
> 
> I have python3 installed and it's aliased as python. Which is confusing me a little bit.

Same problem. How did you fix it?

**Comment by makseq** [comment]
Better to use docker-compose - it has all the environment ML backend needs right out of the box.

**Comment by ODAncona** [comment]
I ran into the same problem trying to run label-studio-ml start:

```bash
label-studio-ml start coco-detector --with \
config_file=mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
checkpoint_file=/absolute/path/to/downloaded/checkpoint.pth
```
The output is:
`sh: 1: python: not found`

in my bashrc I have:

`alias python=python3`

**Comment by lvkaiwei** [comment]
I fix  it  using "ln -s /usr/bin/python3.9 /usr/bin/python"
