### ISSUE TITLE
Unable to annotate images using Tesseract OCR backend

### ISSUE THREAD

**Issue by abhinavkulkarni** [heartexlabs/label-studio-ml-backend#190]
Hi,

I am working on a document AI project wherein I want to tag various items of interest in invoices, such as buyer/seller address, line items, dates, etc., by drawing bounding boxes.

I followed the steps outlined [here](https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/tesseract) - except for cloud storage, I imported a handful of images from local hard disk.

I then started a Tesseract-based OCR backend and added it to project settings.

However, when I click it, I do not see an image in the annotation panel.

Please note I installed label studio using pip inside a virtual environment and started it as `label-studio`. I started the ML backed with the command `label-studio-ml start my-ml-backend -d -p=9090 --debug`. 

What am I missing?

**Comment by makseq** [comment]
@abhinavkulkarni 

> However, when I click it, I do not see an image in the annotation panel.

What do you mean? Could you share a screenshot?

**Comment by juhonkang** [comment]
![image](https://user-images.githubusercontent.com/67153600/226347312-a7c54800-0fd5-4d7b-8d3b-802abf149dc5.png)
Yes, I see the same :(

**Comment by juhonkang** [comment]
<View>
  <View style="display:flex;align-items:start;gap:0px;flex-direction:column-reverse">
    <View style="padding:0px; border: 1px solid #555;">
    	<Image name="image" value="$ocr" zoom="true" zoomControl="false" rotateControl="true" width="100%" height="100%" maxHeight="auto" maxWidth="auto"/>
    </View>
    <RectangleLabels name="bbox" toName="image" strokeWidth="1" smart="true">
      <Label value="Label1" background="green"/>
      <Label value="Label2" background="blue"/>
      <Label value="Label3" background="red"/>
    </RectangleLabels>
  </View>
  	<TextArea name="transcription" toName="image" editable="true" perRegion="true" required="false" maxSubmissions="1" rows="5" placeholder="Recognized Text" displayMode="region-list"/>
</View>

This view not gonna work :(

**Comment by makseq** [comment]
Please use this labeling config:
```
<View>    
   <Image name="image" value="$ocr" zoom="true" zoomControl="false" rotateControl="true" width="100%" height="100%" maxHeight="auto" maxWidth="auto"/>
   
   <RectangleLabels name="bbox" toName="image" strokeWidth="1" smart="true">
      <Label value="Label1" background="green"/>
      <Label value="Label2" background="blue"/>
      <Label value="Label3" background="red"/>
   </RectangleLabels>
   <TextArea name="transcription" toName="image" 
     editable="true" perRegion="true" required="false" 
     maxSubmissions="1" rows="5" placeholder="Recognized Text" 
     displayMode="region-list"/>
</View>
```

I've fixed the readme file with this config. Seems it's a bug in UI.
