### ISSUE TITLE
The 'ruamel.yaml>=0.15.34' distribution was not found and is required by drf-yasg

### ISSUE THREAD

**Issue by hj1643** [heartexlabs/label-studio-ml-backend#22]
Hi, I was trying to set up the ML-backend as follow the QuickStart. When initializing using this code:

label-studio-ml init my_ml_backend --script label_studio_ml/examples/simple_text_classifier.py

I have this problem
![image](https://user-images.githubusercontent.com/84298851/118424826-85ee5380-b6fa-11eb-825a-678ac907afe5.png)

When I check the site-packages I have both 'ruamel.yaml.clib-0.2.2.dist-info' and 'ruamel_yaml' installed. May I know how to solve this? Thanks.

**Comment by makseq** [comment]
Hi, please, check this issue, hope it'll help. 

https://github.com/heartexlabs/label-studio/issues/675#issuecomment-802585890

**Comment by makseq** [comment]
Closed as outdated, solved or not actual issues.
