### ISSUE TITLE
how can we work with enterprise version of label studio to leverage label studio's active learning feature? when i connect ml-backend (from localhost) raised error "can't connect to localhost", is thare any solution?      

### ISSUE THREAD

**Issue by swatijibhkatesj** [heartexlabs/label-studio-ml-backend#229]

**Comment by makseq** [comment]
@swatijibhkatesj you have to expose your ML backend outside of your network. E.g. you can use ngrok like in this example: https://labelstud.io/guide/start.html#Expose-a-local-Label-Studio-instance-outside-using-ngrok
