### ISSUE TITLE
The provided Labeling Interface doesn't work

### ISSUE THREAD

**Issue by csanadpoda** [heartexlabs/label-studio-ml-backend#235]
Using the layout added in the documentation, the image being edited doesn't show:
![image](https://user-images.githubusercontent.com/17254090/228247387-dfbbf17c-db15-4f4e-8dfc-4bc0c3f78f1c.png)
How can I fix it so I can actually see the image I'm trying to annotate?

**Comment by makseq** [comment]
This happened because of wrong styles in Views, just remove all `style=""` from this labeling config.
