### ISSUE TITLE
multi-page annotation ML Backend

### ISSUE THREAD

**Issue by juhonkang** [heartexlabs/label-studio-ml-backend#237]
This is the labeling interface I used, how to connect the tesseract backend for this?

```
<View>
  <Repeater on="$document" indexFlag="{{idx}}" mode="pagination">
      <Image name="page_{{idx}}" value="$document[{{idx}}].page" inline="true"/>

    	<Labels name="labels_{{idx}}" toName="page_{{idx}}">
            <Label value="Text" background="green"/>
            <Label value="Handwriting" background="blue"/>
      	</Labels>
    
      <Rectangle name="bbox_{{idx}}" smart="true" toName="page_{{idx}}" strokeWidth="3"/>
		
      <TextArea name="transcription_{{idx}}" toName="page_{{idx}}"
            editable="true"
            perRegion="true"
            required="true"
            maxSubmissions="1"
            rows="5"
            placeholder="Recognized Text"
            displayMode="region-list"
            />

      <View style="display: flex; justify-content: center;">
        <Header value=" Rate this page:"/>
        <Rating name="rating_{{idx}}" toName="page_{{idx}}"/>
      </View>
  </Repeater>
</View>


<!-- {
"document": [
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0001.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0002.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0003.jpg"
    }
  ]
} -->
```

**Comment by makseq** [comment]
You have modify tesseract ml backend here:
https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/tesseract/tesseract.py#L50

to_name / from_name should be rethinked.

**Comment by juhonkang** [comment]
Another thing is I added the json input with local file path instead of URL, it don't works. Is there anyways?

**Comment by makseq** [comment]
Check this:
https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references

**Comment by juhonkang** [comment]
And one more question is how can get the idx from the context?

**Comment by makseq** [comment]
Sorry what context do you mean?

**Comment by juhonkang** [comment]
@makseq 
![image](https://user-images.githubusercontent.com/67153600/235360714-6e428984-cbb1-4f38-a9ef-5a4bd3105926.png)
To send the text to the right textarea tag in the 
<TextArea name="transcription_{{idx}}", toName="page_{{idx}}">

You need to know the idx of the page you annotate, right?
But how to find the idx of that page?

**Comment by makseq** [comment]
You have `<Image name="page_{{idx}}" value="$document[{{idx}}].page" inline="true"/>` in your labeling config, this image serves some specific page. When you annotate this image, labels with this image ids will be created. TextArea should be linked with this image too, so it will be `toName="page_12"` from `Image name="page_12"`.
