### ISSUE TITLE
How to run ML backend in the Google Colab ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [heartexlabs/label-studio-ml-backend#247]
How to run ML backend in the Google Colab ?

If anyone has any leads in this directions please let me know.

Thanks.

**Comment by makseq** [comment]
Have you checked this docs - https://github.com/heartexlabs/label-studio-ml-backend#deploy-your-ml-backend-to-gcp ?

**Comment by makseq** [comment]
Try to install label-studio-ml-backend package there and implement you class in collab the same way as it's done e.g. here:
https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/dummy_model/dummy_model.py#L6
