### ISSUE TITLE
Gathering metrics in label-studio gui

### ISSUE THREAD

**Issue by enfild** [heartexlabs/label-studio-ml-backend#251]
Hi! Do you have a plans for add metrics to label studio ml backend?

**Comment by makseq** [comment]
What metrics do you expect ot see

**Comment by enfild** [comment]
i mean custom metrics. For example i want to append mAP50 from my training scripts to gui. So i can return `model_path` and `custom_metric` which will show in text blok or somthing like this.

**Comment by makseq** [comment]
We don't have this specific plans, but you can easily add TextArea to your labeling configuration and pre-fill it with values from ML backend with some metric values. Do you mean something like this?

**Comment by enfild** [comment]
@makseq yes i do

**Comment by makseq** [comment]
Does it solve your problem?

**Comment by enfild** [comment]
Yes i found your's examples, thank you.
May be somebody needs:
https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/the_simplest_backend/model.py
```
return {
                'prediction_example': prediction_example,
                'also you can put': 'any artefact here'
            }
```
