### ISSUE TITLE
Doesn't install default_configs, because of missing MANIFEST.in file

### ISSUE THREAD

**Issue by buhrmann** [heartexlabs/label-studio-ml-backend#28]
See here: https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html e.g.

This also makes label-studio-transformers fail, as the first thing to do according to its README is

``` bash
label-studio-ml init my-ml-backend --script models/bert_classifier.py  
```
which fails because it can't find the `default_configs` folder

**Comment by makseq** [comment]
Please use docker-compose to run bert from the label-studio-ml-backend repo.
