### ISSUE TITLE
Request not defined in exceptions file

### ISSUE THREAD

**Issue by himan2411** [heartexlabs/label-studio-ml-backend#3]
Line no 17 in exceptions.py:` a.update({'request': request.args})`
Uses request object which is not defined in internal variable and also not imported as form of library. It is throwing an exception becuase of that.

**Comment by antonyscerri** [comment]
Ran into the same thing, it's unclear if this version is meant to be working yet alongside the 1.0.0 release of label studio. To fix it i had to add the following to exceptions.py:

`from flask import Flask, request, jsonify, send_file`

I also had to remove the call to make_response further down (just returning its two arguments as-is). That seemed to get things running to some degree.

**Comment by niklub** [comment]
Hey, guys. Fixed in 3c5d93b8295e9d761cec5a2183f5464f980cf17d . Some things could still gonna happen due to migration from the main Label Studio repo, but hope they go away pretty soon. Let me know if it happens again

**Comment by antonyscerri** [comment]
Thanks for patching that. Right now is predicting using a mode supported in any way, i've yet to find a "predict" button in the 1.0.0 release UI and ive tried various project configs and ml backends and the sampling cli arg which only supports sequential and random but not the min/max ones mentioned in the documents. So its a bit tricky trying to work out what should be working and whether its a bug or not.

**Comment by himan2411** [comment]
Hello ,

Thanks for patching the requested changes, that too so quickly, but 
 Using the posted commit, there are still some issues with exceptions.py file.
When I clicked on start training from UI, this is the stack trace I got:
`  File "~/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "~/label-studio-ml-backend/label_studio_ml/api.py", line 62, in _train
    job = _manager.train(completions, project, label_config, **params)
  File "~/label-studio-ml-backend/label_studio_ml/model.py", line 368, in train
    project, label_config, train_kwargs=kwargs, tasks=tasks)
  File "~/label-studio-ml-backend/label_studio_ml/model.py", line 323, in train_script_wrapper
    train_output = m.model.fit(data_stream, workdir, **train_kwargs)
TypeError: fit() takes 2 positional arguments but 3 were given

Traceback (most recent call last):
  File "~/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "~/label-studio-ml-backend/label_studio_ml/api.py", line 62, in _train
    job = _manager.train(completions, project, label_config, **params)
  File "~/label-studio-ml-backend/label_studio_ml/model.py", line 368, in train
    project, label_config, train_kwargs=kwargs, tasks=tasks)
  File "~/label-studio-ml-backend/label_studio_ml/model.py", line 323, in train_script_wrapper
    train_output = m.model.fit(data_stream, workdir, **train_kwargs)
TypeError: fit() takes 2 positional arguments but 3 were given
`
Not sure what's wring here.
