### ISSUE TITLE
Unable to start ml-backend docker

### ISSUE THREAD

**Issue by StefosGeo** [heartexlabs/label-studio-ml-backend#33]
Hi, I am trying to run the ml-backend on docker but I am facing an error. After following the instructions I ran the following commands:

`label-studio-ml init my_ml_backend3 --script label_studio_ml/examples/tensorflow/mobilenet_finetune.py:TFMobileNet`

and then tried `docker-compose up`

But i got the following error:

> Starting redis ... done
Starting server ... done
Attaching to redis, server
redis     | 1:C 02 Sep 2021 13:36:41.376 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 02 Sep 2021 13:36:41.376 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 02 Sep 2021 13:36:41.376 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis     | 1:M 02 Sep 2021 13:36:41.376 * monotonic clock: POSIX clock_gettime
redis     | 1:M 02 Sep 2021 13:36:41.377 * Running mode=standalone, port=6379.
redis     | 1:M 02 Sep 2021 13:36:41.377 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis     | 1:M 02 Sep 2021 13:36:41.377 # Server initialized
redis     | 1:M 02 Sep 2021 13:36:41.377 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis     | 1:M 02 Sep 2021 13:36:41.377 * Loading RDB produced by version 6.2.5
redis     | 1:M 02 Sep 2021 13:36:41.377 * RDB age 4 seconds
redis     | 1:M 02 Sep 2021 13:36:41.377 * RDB memory usage when created 0.77 Mb
redis     | 1:M 02 Sep 2021 13:36:41.377 * DB loaded from disk: 0.000 seconds
redis     | 1:M 02 Sep 2021 13:36:41.377 * Ready to accept connections
server    | 2021-09-02 13:36:42,704 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
server    | 2021-09-02 13:36:42,708 INFO RPC interface 'supervisor' initialized
server    | 2021-09-02 13:36:42,708 CRIT Server 'inet_http_server' running without any HTTP authentication checking
server    | 2021-09-02 13:36:42,708 INFO supervisord started with pid 1
server    | 2021-09-02 13:36:43,711 INFO spawned: 'rq_00' with pid 9
server    | 2021-09-02 13:36:43,712 INFO spawned: 'wsgi' with pid 10
server    | 2021-09-02 13:36:43,788 INFO exited: rq_00 (exit status 1; not expected)
server    | 2021-09-02 13:36:44,791 INFO spawned: 'rq_00' with pid 25
server    | 2021-09-02 13:36:44,791 INFO success: wsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
server    | 2021-09-02 13:36:44,864 INFO exited: rq_00 (exit status 1; not expected)
server    | 2021-09-02 13:36:46,867 INFO spawned: 'rq_00' with pid 26
server    | 2021-09-02 13:36:46,974 INFO exited: rq_00 (exit status 1; not expected)
server    | 2021-09-02 13:36:49,979 INFO spawned: 'rq_00' with pid 27
server    | 2021-09-02 13:36:50,059 INFO exited: rq_00 (exit status 1; not expected)
server    | 2021-09-02 13:36:51,060 INFO gave up: rq_00 entered FATAL state, too many start retries too quickly

and

> Traceback (most recent call last):
  File "/usr/local/bin/rq", line 5, in <module>
    from rq.cli import main
  File "/usr/local/lib/python3.7/site-packages/rq/cli/__init__.py", line 2, in <module>
    from .cli import main
  File "/usr/local/lib/python3.7/site-packages/rq/cli/cli.py", line 93, in <module>
    @pass_cli_config
  File "/usr/local/lib/python3.7/site-packages/rq/cli/cli.py", line 72, in pass_cli_config
    func = option(func)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.

Thank you in advance.

**Comment by KonstantinKorotaev** [comment]
Hi @StefosGeo 
Fixed in latest master
