### ISSUE TITLE
image semantic segmentation ml backend example?

### ISSUE THREAD

**Issue by imean131415** [heartexlabs/label-studio-ml-backend#49]
Is there an example for image semantic segmentation ml backend? I am not sure, how to write the predict results to adapt to label studio. Thank you!

**Comment by makseq** [comment]
Please check this docs
https://labelstud.io/tutorials/object-detector.html

And also this video might be helpful
https://youtu.be/CyRe73VD4EE

**Comment by KonstantinKorotaev** [comment]
Ho @imean131415 
You can check this [example](https://github.com/heartexlabs/label-studio-ml-backend/pull/27/files#diff-ea03d0d3a4de296d15764bb9737fb23ec2935b746e6b2235e68b2269bd09cbee).
The main point is to use **encode_rle** method to convert the mask to RLE format that is used in Label Studio.

**Comment by LetSur** [comment]
Hi @KonstantinKorotaev 
I try to implement the referred example.
How can I pass 'context' that contains interaction information (i.e., point or bounding box) to predict function?
Thank you in advance! 
Thank you!

**Comment by KonstantinKorotaev** [comment]
Hi @LetSur 
You should use Webhook feature from Label Studio - it has all necessary data including context

**Comment by makseq** [comment]
Also please check this issue, it might be useful - https://github.com/heartexlabs/label-studio/issues/732#issuecomment-810731402

**Comment by makseq** [comment]
Closed as outdated, solved or no more actual issue.
