### ISSUE TITLE
docker-compose up -d, unable to copy *.py /app, interanl server error

### ISSUE THREAD

**Issue by Asamasach** [heartexlabs/label-studio-ml-backend#57]
Hi, I've done docker-compose up -d  on default_configs
but it except with: unable to copy *.py /app, internal server error in Dockerfile which seems correct (as there is no .py)
I've copied the up directory/*.py there and it said no error, but the curl return internal server error

**Comment by makseq** [comment]
Closed as outdated, solved or no more actual issue.
