### ISSUE TITLE
Example tensorflow

### ISSUE THREAD

**Issue by mops1112** [heartexlabs/label-studio-ml-backend#59]
Hi,
can I apply TensorFlow examples for multiple object detection rectangles for pre-annotation?

**Comment by makseq** [comment]
@mops1112 If you are talking about this https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/tensorflow/mobilenet_finetune.py --- then it's a choice classification model. It's not applicable for the object detection task.

**Comment by makseq** [comment]
Feel free to reopen if you have questions.
