### ISSUE TITLE
How return format json pre-annotation

### ISSUE THREAD

**Issue by mops1112** [heartexlabs/label-studio-ml-backend#60]
Hi,
my_backend send this json--> to label-studio
{'annotations': [{'result': [{'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.07965517044067383, 'y': 0.08535835891962051, 'width': 0.0035918901364008584, 'height': 0.027162909507751465}, 'score': 0.98451}, {'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.06727302074432373, 'y': 0.11262299865484238, 'width': 0.0160603125890096, 'height': 0.011844754219055176}, 'score': 0.98362213}, {'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.06980470816294353, 'y': 0.07412908226251602, 'width': 0.013376221060752867, 'height': 0.025176003575325016}, 'score': 0.9786032}, {'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.044702822963396706, 'y': 0.0858452245593071, 'width': 0.015623619159062704, 'height': 0.026315413415431973}, 'score': 0.9712106}, {'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.015116376181443533, 'y': 0.07554244995117188, 'width': 0.013097770512104034, 'height': 0.021875575184822083}, 'score': 0.9607427}, {'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'rectanglelabels': ['car'], 'x': 0.06571339070796967, 'y': 0.010496671311557293, 'width': 0.005934014916419983, 'height': 0.00786984246224165}, 'score': 0.9527463}]}]}

but it shows message TypeError: Object of type float32 is not JSON serializable.
so, I return json.dumps(str(msg)) instead.
but,label-studio doest not show any bounding box.

that JSON-format is correct?

**Comment by makseq** [comment]
Convert your values to `float` like this: 
```
bboxes = np.array(bboxes, dtype=float)

value = {
  'rectanglelabels': ['car'], 
  'x': bboxes[0], 
  'y': bboxes[1], 
  'width': bboxes[2], 
  'height': bboxes[3]
}

... 

```

**Comment by mops1112** [comment]
![image](https://user-images.githubusercontent.com/26622116/141235182-48ff66a9-8227-4ce6-8077-b8bc7ddcb251.png)
it shows the label and score but it does not bounding-box on the image?

**Comment by makseq** [comment]
@mops1112 
Try to add id for the each region, e.g.:

```
{'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 
'value': {'rectanglelabels': ['car'], 'x': 0.07965517044067383, 'y': 0.08535835891962051, 'width': 0.0035918901364008584, 'height': 0.027162909507751465}, 'score': 0.98451}
```
=>
```
{'id': 'some-random-number', 'from_name': 'label', 'to_name': 'image', 'type': 'rectanglelabels', 
'value': {'rectanglelabels': ['car'], 'x': 0.07965517044067383, 'y': 0.08535835891962051, 'width': 0.0035918901364008584, 'height': 0.027162909507751465}, 'score': 0.98451}
```
