### ISSUE TITLE
get_local_path provides path without the project_id [FileNotFoundError]

### ISSUE THREAD

**Issue by krnithishkumar** [heartexlabs/label-studio-ml-backend#61]
For the custom ML model, we used to get the uploaded file path using `get_local_path` on passing the file URL https://github.com/heartexlabs/label-studio-ml-backend/blob/94750ca7233b6f07ff7cb8986160ba9ea1b4ed91/label_studio_ml/model.py#L297

### Current behaviour:
It provides the incorrect file path without the project ID.<br>
The file is uploaded within `C:\\Users\\uname1\\AppData\\Local\\label-studio\\label-studio\\media\\upload\\1\\3f3daefd-sampledata.wav`. 
After the `upload` folder we have subfolder `1` that represents the project id.

While getting file_path using `get_local_path`. It provides without the project id, `C:\\Users\\uname1\\AppData\\Local\\label-studio\\label-studio\\media\\upload\\1\\3f3daefd-sampledata.wav`

### Tested Environment:
Windows 10

### Screenshot:
![image](https://user-images.githubusercontent.com/29236082/141763295-5240182f-64fe-4c9e-acc8-85fe0f5a67df.png)

**Comment by KonstantinKorotaev** [comment]
Hi @krnithishkumar 
Thank you for your contribution to Label Studio, I have merged your pull request.
