### ISSUE TITLE
Predict request is getting called twice

### ISSUE THREAD

**Issue by krnithishkumar** [heartexlabs/label-studio-ml-backend#64]
For the Custom-model integration with the label studio, the prediction is working fine.
The issue is the `predict()` method is getting called twice. So that two times the model is getting the inference for the prediction.
This happens when I load the file for the annotation. Kindly suggest some ideas to overcome two times predication to one time.

With the below logs, You can able to see the POST method for `predict` is getting called twice for the same file.
![image](https://user-images.githubusercontent.com/29236082/142184169-920bb4a7-b2b8-4635-bc6e-bbe0e942e881.png)

**Comment by krnithishkumar** [comment]
Internally the Label-Studio resend the request after the following warning occurs,
`[2021-11-18 05:22:20,285] [ml.models::predict_tasks::183] [WARNING] 'ML backend 'Staged Model' doesn't support batch processing of tasks, switched to one-by-one task retrieval`

**Comment by pneumoman** [comment]
Are you processing only one task?  
the code does not check that there is only one task being processed

it should be comparing the response size to the tasklist size but it doesn't

https://github.com/heartexlabs/label-studio/blob/e207e3d8a03d9059978625bcb77fb796380b6283/label_studio/ml/models.py#L183-L190

**Comment by krnithishkumar** [comment]
Yes @pneumoman, With the blow preferences.

![image](https://user-images.githubusercontent.com/29236082/142564824-382dc6d2-b6a1-4fcd-af63-2972ee74c210.png)

I am trying to do auto-prediction when I click for the particular file and not for a batch of files.

This [code](https://github.com/heartexlabs/label-studio/blob/e207e3d8a03d9059978625bcb77fb796380b6283/label_studio/ml/models.py#L188) should check for the length of tasks that should be 1 if is more than 1 it can move for the one-by-one task retrieval.

**Comment by makseq** [comment]
Fixed in LS 1.4
