### ISSUE TITLE
Error: sh 1: python not found

### ISSUE THREAD

**Issue by rm-data-viz** [heartexlabs/label-studio-ml-backend#7]
https://github.com/heartexlabs/label-studio-ml-backend/blob/4989ef5adf3673e3d41fac67964b90298ac07573/label_studio_ml/server.py#L112

I believe it should be:

`os.system('python3 '  + wsgi + '  ' +'  '.join(subprocess_params))`

What are your thoughts?

**Comment by rm-data-viz** [comment]
### ### ### ****

**Comment by jonatassalgado** [comment]
I get the same error in version 1.0.1. Before, in old version, I had a lot ml services running, but until now I spend a few hours and I not figure out how to trespassing this issue :(

Nothing different in logs  at main process / inference uwsgi.log and rq.log

I tried following the simple tutorial in the README at this repo.

**Comment by makseq** [comment]
@jonatassalgado @rm-data-viz Are you using venv or virtualenv? I strongly recommend to do this. Looks like you have some mix of python environments.

**Comment by rm-data-viz** [comment]
@makseq - I'm using the docker version of Label-Studio. I don't think it's associated to python virtual environment.

**Comment by makseq** [comment]
In this case it's weird: LS 1.0 docker doesn't have ML backend at all.

**Comment by rm-data-viz** [comment]
It does have a django ml app. But, to make ml backend work, I cloned the label-studio-ml repository. 

I then initiated the ml_backend, but during label-studio-ml start ml_backend. It throws this error.

**Comment by alex-eurec** [comment]
The same problem is happening to me, I chose not to use venv, because I created a VM with a 'labelstudio' user that will be only running LabelStudio and the ML module.

This is happening in an ubuntu 20.20 server, that only has python3 installed (by default installation).

**Comment by makseq** [comment]
Closed as outdated.
