### ISSUE TITLE
Multi language ml backend

### ISSUE THREAD

**Issue by mathrb** [heartexlabs/label-studio-ml-backend#75]
Hello,

First of all, thanks for the product.
I'd like to host a text ml backend that will be registered by multiple labelstudio projects that use different languages (english, german, french ...)
As of today, it does not seem to be feasible because the instance of LabelStudioMLBase is done here: 
https://github.com/heartexlabs/label-studio-ml-backend/blob/8c2ebaf9543ce569027de0bc1574d2cbe0cd20eb/label_studio_ml/model.py#L67
So no extra arg is fetched from the labelstudio server (which makes sense)
And the train/fit method is called right after 
https://github.com/heartexlabs/label-studio-ml-backend/blob/8c2ebaf9543ce569027de0bc1574d2cbe0cd20eb/label_studio_ml/model.py#L69
additional_params sounded like a good candidate, but get_additional_params returns an empty dict
https://github.com/heartexlabs/label-studio-ml-backend/blob/8c2ebaf9543ce569027de0bc1574d2cbe0cd20eb/label_studio_ml/model.py#L75
Would there be a workaround I did not see, or is it something planned in the future?

Kind regards

**Comment by KonstantinKorotaev** [comment]
Hi @mathrb 
You can do that in __init__ method as label_config can contain different data that you can use as additional params.

**Comment by mathrb** [comment]
Hello @KonstantinKorotaev 
How would I specify in a project the language? Using a custom tag in the html view?

**Comment by KonstantinKorotaev** [comment]
@mathrb does the solution with tags solves your issue?

**Comment by mathrb** [comment]
This would lead to redundant information that could be stored at the project level. 
Today I'm using environment variable to start my ml backend, each project using a different backend based on project language.
