### ISSUE TITLE
TypeError: argument of type 'ModelWrapper' is not iterable

### ISSUE THREAD

**Issue by kemics** [heartexlabs/label-studio-ml-backend#77]
Hello, when I am running backend API I receive the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 66, in _train
    job = _manager.train(annotations, project, label_config, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 646, in train
    cls.get_or_create(project, label_config, force_reload=True, train_output=train_output)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 450, in get_or_create
    if not cls.has_active_model(project) or force_reload or (cls.get(project).model_version != version and version is not None):  # noqa
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 426, in has_active_model
    return cls._key(project) in cls._current_model
TypeError: argument of type 'ModelWrapper' is not iterable
```

I have checked the code and it looks like field `_current_model` sometimes is set as instance of ModelWrapper rather than dictionary:

https://github.com/heartexlabs/label-studio-ml-backend/blob/054854e0bae5b5d4c1d99c68fcf1830db13bb747/label_studio_ml/model.py#L479-L486

### Environment

Project version: https://github.com/heartexlabs/label-studio-ml-backend/tree/054854e0bae5b5d4c1d99c68fcf1830db13bb747

**Comment by niklub** [comment]
Hi, @kemics ! Could you please tell me what's the API endpoint you call in this case? and did you specify `LABEL_STUDIO_ML_BACKEND_V2=true` variable in the env?

**Comment by kemics** [comment]
Hi, @niklub 

I set `LABEL_STUDIO_ML_BACKEND_V2=1`


>what's the API endpoint you call in this case?

I just put API URL in Machine Learning settings of the project. I don't invoke backend API by my own

<img width="615" alt="Screenshot 2022-01-18 at 17 10 14" src="https://user-images.githubusercontent.com/14817537/149953204-1728e91b-4e34-4a4e-a0af-892f232b9d56.png">

**Comment by kemics** [comment]
The problem was with `Start model training after any annotations are submitted or update` (more details here https://github.com/heartexlabs/label-studio-ml-backend/issues/78)

I after unchecking the settings the exception has stopped. So, I'm closing the issue

**Comment by hemangjoshi37a** [comment]
You need to compare that the two are equal, not that one is in the other.

in this file : ` /home/<YOUR_USER_NAME>/anaconda3/lib/python3.8/site-packages/label_studio_ml/model.py`

replace this line : `return cls._key(project) in cls._current_model`
to this line : 
```
are_they_equal = cls._key(project) == cls._current_model
return are_they_equal
```
https://hjlabs.in
