### ISSUE TITLE
How to run stateless custom backend api?

### ISSUE THREAD

**Issue by kemics** [heartexlabs/label-studio-ml-backend#78]
Hello, I am trying to run custom backend API in serverless way. So, it is by default stateless. Moreover, containers are scaled up on demand and scaled down to 0 when there is no workload

All works fine except from model versions. There are multiple problems:

1. Over the time there are a lot of newly created model versions in LabelStudio UI like on the following screenshot:
<img width="296" alt="Screenshot 2022-01-17 at 23 09 02" src="https://user-images.githubusercontent.com/14817537/149831564-a47d8e18-fe86-4c53-9cd3-2368c7681a45.png">

Ideally, I would like to have single version `INITIAL`

2. From time to time there are exceptions like `OSError: Result file /data/models/1642448814/job_result.json specified by model_version doesn't exist`

Is it possible to run stateless custom backend API?

**Comment by makseq** [comment]
@kemics As I remember you can return your model version in the predictions of `predict()` method, e.g.: 

```
def predict(...):
    ...
    predictions = [ { "model_version": "my-only-one", "result": [...], ... }]
    return predictions
```

**Comment by kemics** [comment]
@makseq if I add `model_version` key to prediction then API returns JSON like `{"model_version":"INITIAL","results":[{"model_version":"v0.0.1","result":[],"score":0.0}]}`. Now there are two keys `model_version` on different depth. Is it expected?

**Comment by KonstantinKorotaev** [comment]
Hi @kemics 
Could you please provide your ML configuration in Label Studio?
Do you have a storage for your containers?
Do you reinitialize them each time they go down?

It seems that after you stop them and start over again you are getting new model_version

**Comment by kemics** [comment]
The problem was with setting `Start training after any annotations are submitted or updated` in LabelStudio ML configuration. Right now it works as expected

@KonstantinKorotaev thank you for your help with investigation
