### ISSUE TITLE
confusion caused by versions > 1.0.4

### ISSUE THREAD

**Issue by konradmalik** [heartexlabs/label-studio-ml-backend#93]
Hi,
I have questions regarding the versions of this library after 1.0.4 because I'm confused with how they differ from 1.0.4 and how they should be used.

The Dockerfile and relevant files confuse me. After 1.0.4, the docker setup changed, and the following happened:
- requirements.txt is empty; why? Is this ok? If that's intended, then why still keep it in the first place? Why is there no dependency on gunicorn when it is essential?
- supervisord isn't used anymore
  - If that's the case, why do we still have supervisord.conf in the container?
  - How is training happening? Is it simply using one (or more) of the default eight gunicorn threads? What if I run two simultaneous training jobs? Is it a "race"?
- what happened with Redis support?
  - docker-compose still deploys it
  - If the above regarding training is true, then we don't need redis, right? rq is no longer started via supervisord because there is no supervisord

Could someone familiar with the matter clarify some of the above doubts?
Thanks

**Comment by KonstantinKorotaev** [comment]
Hi @konradmalik 
Could you please clarify how did you install label studio ml backend?
What example do you use?

**Comment by konradmalik** [comment]
Hey, yeah I'm talking about [these](https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/default_configs) files that get copied when invoking `label-studio-ml init` command with versions > 1.0.4.
The presence of redis when it does not seem to be used at first sight (lack of rq), supervisord.conf while it's not started by the container, lack of obvious guinicorn dependency etc., all of this is strange to me.

What I'm used to and what makes sense to me is what happened with version 1.0.4 for example, [those](https://github.com/heartexlabs/label-studio-ml-backend/tree/b6407ba3625780bbb3349c45bbc224749c03e97a/label_studio_ml/default_configs) are the files. rq is used, supervisor is started by the container, dependencies are installed in Dockerfile etc. I'm just not sure what changed in the new versions and why it looks like the config and template files ale halfway through the transition to the new version of the library.

To add, my model is build mainly based on [that](https://github.com/heartexlabs/label-studio-ml-backend/tree/b6407ba3625780bbb3349c45bbc224749c03e97a/label_studio_ml/examples/simple_text_classifier) example but I'm not sure if that's relevant.

**Comment by KonstantinKorotaev** [comment]
@konradmalik we are moving all requirements to examples itself, but I will add gunicorn and redis in default requirements file.
You can take fix from [here](https://github.com/heartexlabs/label-studio-ml-backend/pull/94).

**Comment by konradmalik** [comment]
Thanks, cool. So if I understand correctly that:
- supervisor is no longer used
- rq is simply used directly by label-studio-ml package
then all is clear now 🙂
