### ISSUE TITLE
Attributes not initialized in Transformers NER example through docker-compose.

### ISSUE THREAD

**Issue by elonmusk-01** [heartexlabs/label-studio-ml-backend#98]
Hi, I am using the fix/transformers-bert branch and trying to run the ner backend through docker-compose. If it is as simple as docker-compose up still I am facing errors.
Here is my logs :
![Screenshot from 2022-03-15 22-11-37](https://user-images.githubusercontent.com/98889224/158528736-de4c1b14-f72e-442e-8686-c223ac4a0858.png)

**Comment by elonmusk-01** [comment]
The predict() method of TransformersBasedTager class have this error and I need help to get a working NER example using transformers models as backend. Also do I need to specify any model or the backend have default model in scripts??

**Comment by KonstantinKorotaev** [comment]
Hi @elonmusk-01 
I have fixed the issue in https://github.com/heartexlabs/label-studio-ml-backend
Check ner example

**Comment by makseq** [comment]
Closed as outdated, solved or no more actual issue.
