### ISSUE TITLE
fit() call with no tasks

### ISSUE THREAD

**Issue by michelemoretti** [heartexlabs/label-studio-ml-backend#99]
Hi Everybody,

it seems like my ml backend is receiving the fit signals but no tasks are associated (the first argument is an empty tuple)
The culprit seems to be [this line](https://github.com/heartexlabs/label-studio-ml-backend/blob/9e8728a9aba11b8385e501428b4421c819ef1839/label_studio_ml/model.py#L312) that I can't make sense of.
When a train event is received the object calls the fit method... with an empty tuple as argument, and that's why I receive an empty tuple.

Where are the tasks?
What am I missing?

Thank you in advance

**Comment by michelemoretti** [comment]
I do use label studio, and digging I just read that since 1.4.1 the behaviour of label-studio changed and instead of calling the _train method of Flask a webhook is called. Is this what's breaking my previously working code?

Is label-studio-ml-backend updated with the latest behaviour of label-studio?

**Comment by michelemoretti** [comment]
To give even more context, I am running a docker-compose with 4 bridged services: 

- label-studio
- postgresql
- label-studio-ml-backend
- redis

Basically my LabelStudioMLBase.fit() function is defined as 
def fit(self,tasks,**kwargs):
    ...

and when the Start Training button is pressed in the label-studio interface, the browser calls the label-studio api at the /api/ml/{ml_backend_id}/train endpoint, which queues a job on RQ; 

But when the RQ job is processed, what the fit function receives is an empty Tuple for tasks (coherent with [the line highlighted in the issue](https://github.com/heartexlabs/label-studio-ml-backend/blob/9e8728a9aba11b8385e501428b4421c819ef1839/label_studio_ml/model.py#L312)) and the following kwargs dict (some info redacted '...')

```json
{
    "event": "PROJECT_UPDATED",
    "data": {
        "project": {
            "id": 1,
            "task_number": 5,
            "finished_task_number": 5,
            "total_predictions_number": 0,
            "total_annotations_number": 5,
            "num_tasks_with_annotations": 5,
            "useful_annotation_number": 5,
            "ground_truth_number": 0,
            "skipped_annotations_number": 0,
            "title": ...,
            "description": "",
            "label_config": ...,
            "parsed_label_config":...,
        },
        "expert_instruction": "",
        "show_instruction": False,
        "show_skip_button": True,
        "enable_empty_annotation": True,
        "reveal_preannotations_interactively": False,
        "show_annotation_history": False,
        "show_collab_predictions": True,
        "evaluate_predictions_automatically": False,
        "token": ...,
        "result_count": 0,
        "color": "#FFFFFF",
        "maximum_annotations": 1,
        "min_annotations_to_start_training": 0,
        "control_weights": ...,
        "model_version": "INITIAL",
        "data_types": {
            "image": "Image",
            "image_name": "Text"
        },
        "is_draft": False,
        "is_published": False,
        "created_at": ...,
        "updated_at": ...,
        "sampling": "Sequential sampling",
        "skip_queue": "REQUEUE_FOR_OTHERS",
        "show_ground_truth_first": False,
        "show_overlap_first": False,
        "overlap_cohort_percentage": 100,
        "task_data_login": ...,
        "task_data_password": ...,
        "organization": 1,
        "created_by": 1
    },
    "job_id": "1648737854",
    "workdir": "/data/models/1648737854"
}
```

Am I misunderstanding some step or missing something? Am I supposed to access the jsons and parse them directly from label-studio-ml-backend now?

**Comment by KonstantinKorotaev** [comment]
It seems that you invoke training with webhook. Please check [this article](https://labelstud.io/guide/ml_create.html#Trigger-training-with-webhooks) to fix the issue.

**Comment by michelemoretti** [comment]
Exactly! Thank you so much for the link.
So it IS intended behaviour starting from label-studio 1.4.1 correct?

I'll try to implement one of the solutions proposed, but it looks to me like that backward incompatible change should be reflected in this repo's docs at least by not assuming that the fit() method would receive the tasks right?

In any case, thanks for the clarification and the help. If what I suggested up there makes no sense to you we can close this issue.

**Comment by KonstantinKorotaev** [comment]
Yes, it's intended behaviour starting from label-studio 1.4.1.
If you want to enable previous behavior, run LS with this env flag:
ff_back_dev_1417_start_training_mlbackend_webhooks_250122_long=1 label-studio

**Comment by lglong123** [comment]
so, How to use API to get all annotated tasks?

Thanks.

**Comment by KonstantinKorotaev** [comment]
> How to use API to get all annotated tasks?

@lglong123 you can use this [example](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/simple_text_classifier/simple_text_classifier.py#L95)
